name: test
on:
  pull_request:

jobs:
  test:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
      fail-fast: true

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install deps
      run: python -m pip install tox poetry tox-poetry
    - name: test
      run: tox -e test
    - name: upload cov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
